/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppPanel: typeof import('./src/components/AppPanel.vue')['default']
    AppView: typeof import('./src/components/AppView.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UiBtn: typeof import('./../ui/src/components/UiBtn/UiBtn.vue')['default']
    UiCheckbox: typeof import('./../ui/src/components/UiCheckbox/UiCheckbox.vue')['default']
    UiIcon: typeof import('./../ui/src/components/UiIcon/UiIcon.vue')['default']
    UiOverlayMenu: typeof import('./../ui/src/components/UiOverlayMenu/UiOverlayMenu.vue')['default']
    UiPopup: typeof import('./../ui/src/components/UiOverlayMenu/UiPopup.vue')['default']
    UiTextField: typeof import('./../ui/src/components/UiTextField/UiTextField.vue')['default']
  }
}
