/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UiBtn: typeof import('./src/components/UiBtn/UiBtn.vue')['default']
    UiIcon: typeof import('./src/components/UiIcon/UiIcon.vue')['default']
    UiOverlayMenu: typeof import('./src/components/UiOverlayMenu/UiOverlayMenu.vue')['default']
    UiPopup: typeof import('./src/components/UiOverlayMenu/UiPopup.vue')['default']
  }
}
